-- 002_dynamic.sql — Dinamik içerik platformu için yeni tablolar + Settings ALTER.
-- Append-only; mevcut Settings/Categories/Contents/Links kırılmaz.
-- Çalıştırma: psql "$DATABASE_URL" -f deploy/migrations/002_dynamic.sql

BEGIN;

-- ──────────────────────────────────────────────────────────────
-- Users: admin/editor hesapları
CREATE TABLE IF NOT EXISTS "Users" (
  "UserID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Email"         TEXT UNIQUE NOT NULL,
  "Username"      TEXT UNIQUE,
  "PasswordHash"  TEXT NOT NULL,
  "DisplayName"   TEXT,
  "Role"          TEXT NOT NULL DEFAULT 'editor',
  "AvatarURL"     TEXT,
  "LastLoginAt"   TIMESTAMP,
  "IsActive"      BOOLEAN DEFAULT TRUE,
  "IsDeleted"     BOOLEAN DEFAULT FALSE,
  "CreatedDate"   TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"     INTEGER
);

-- ──────────────────────────────────────────────────────────────
-- ApiKeys: provider anahtarları (AES-GCM şifreli saklanır)
CREATE TABLE IF NOT EXISTS "ApiKeys" (
  "ApiKeyID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Provider"      TEXT NOT NULL,
  "Purpose"       TEXT NOT NULL,
  "Label"         TEXT,
  "KeyValue"      TEXT NOT NULL,
  "Config"        JSONB DEFAULT '{}'::jsonb,
  "IsActive"      BOOLEAN DEFAULT FALSE,
  "IsDeleted"     BOOLEAN DEFAULT FALSE,
  "CreatedDate"   TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"     INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_apikeys_active_per_purpose"
  ON "ApiKeys" ("Provider", "Purpose")
  WHERE "IsActive" = TRUE AND "IsDeleted" = FALSE;

-- ──────────────────────────────────────────────────────────────
-- CronJobs: kategori-bazlı planlanmış ingest işleri
CREATE TABLE IF NOT EXISTS "CronJobs" (
  "CronID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "JobName"         TEXT NOT NULL,
  "FK_CatID"        INTEGER,
  "NewsProvider"    TEXT,
  "TextAiProvider"  TEXT,
  "ImageAiProvider" TEXT,
  "FrequencyCron"   TEXT NOT NULL,
  "ArticlesPerRun"  INTEGER DEFAULT 3,
  "LastRunAt"       TIMESTAMP,
  "LastRunStatus"   TEXT,
  "LastRunMessage"  TEXT,
  "NextRunAt"       TIMESTAMP,
  "IsActive"        BOOLEAN DEFAULT TRUE,
  "IsDeleted"       BOOLEAN DEFAULT FALSE,
  "CreatedDate"     TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"       INTEGER
);
CREATE INDEX IF NOT EXISTS "idx_cronjobs_due"
  ON "CronJobs" ("NextRunAt")
  WHERE "IsActive" = TRUE AND "IsDeleted" = FALSE;

-- ──────────────────────────────────────────────────────────────
-- Themes: homepage şablon varyantları
CREATE TABLE IF NOT EXISTS "Themes" (
  "ThemeID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ThemeSlug"     TEXT UNIQUE NOT NULL,
  "ThemeName"     TEXT NOT NULL,
  "ThemeDesc"     TEXT,
  "PreviewImage"  TEXT,
  "Config"        JSONB DEFAULT '{}'::jsonb,
  "SupportsDark"  BOOLEAN DEFAULT TRUE,
  "IsActive"      BOOLEAN DEFAULT TRUE,
  "IsDeleted"     BOOLEAN DEFAULT FALSE,
  "CreatedDate"   TIMESTAMP DEFAULT NOW()
);
INSERT INTO "Themes" ("ThemeSlug", "ThemeName", "ThemeDesc", "SupportsDark") VALUES
  ('classic',  'Classic',  'Varsayılan hero + grid',                TRUE),
  ('magazine', 'Magazine', '2 kolonlu büyük kapak + yan sidebar',   TRUE),
  ('minimal',  'Minimal',  'Tek kolon yalın liste',                 TRUE)
ON CONFLICT ("ThemeSlug") DO NOTHING;

-- ──────────────────────────────────────────────────────────────
-- IngestRuns: her ingest çalıştırmasının logu (dashboard bunu okur)
CREATE TABLE IF NOT EXISTS "IngestRuns" (
  "RunID"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_CronID"   INTEGER,
  "FK_CatID"    INTEGER,
  "StartedAt"   TIMESTAMP DEFAULT NOW(),
  "FinishedAt"  TIMESTAMP,
  "Inserted"    INTEGER DEFAULT 0,
  "Skipped"     INTEGER DEFAULT 0,
  "Errored"     INTEGER DEFAULT 0,
  "Status"      TEXT,
  "Log"         TEXT
);
CREATE INDEX IF NOT EXISTS "idx_ingestruns_started" ON "IngestRuns" ("StartedAt" DESC);

-- ──────────────────────────────────────────────────────────────
-- Settings genişletme (additive)
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "GoogleAnalyticsID"  TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "GoogleTagManagerID" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "SearchConsoleMeta"  TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "BingVerification"   TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "DefaultOgImage"     TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "TwitterHandle"      TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "MetaAuthor"         TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "MetaRobots"         TEXT DEFAULT 'index,follow';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "FK_ThemeID"         INTEGER;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "DefaultColorMode"   TEXT DEFAULT 'light';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AllowColorToggle"   BOOLEAN DEFAULT TRUE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "LlmsTxtEnabled"     BOOLEAN DEFAULT TRUE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "LlmsTxtIntro"       TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "SocialLinks"        JSONB DEFAULT '[]'::jsonb;

-- GoogleKit: AdSense + yardımcı Google ayarları
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AdsensePublisherID" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AdsenseAutoAds"     BOOLEAN DEFAULT FALSE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AdsenseExtraHead"   TEXT;

-- Search Console Indexing API: servis hesabı JSON + toggle
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "IndexingEnabled"            BOOLEAN DEFAULT FALSE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "IndexingServiceAccountJSON" TEXT;

-- ──────────────────────────────────────────────────────────────
-- Contents: AI image üretimi için son kullanılan prompt saklansın
ALTER TABLE "Contents" ADD COLUMN IF NOT EXISTS "ImagePrompt" TEXT;
-- Okunma sayacı (client beacon → in-memory buffer → batch UPDATE ile artar)
ALTER TABLE "Contents" ADD COLUMN IF NOT EXISTS "ViewCount" BIGINT DEFAULT 0;
CREATE INDEX IF NOT EXISTS "idx_contents_viewcount"
  ON "Contents" ("ViewCount" DESC)
  WHERE "IsActive" = TRUE AND "IsDeleted" = FALSE;

-- Varsayılan aktif tema = classic
UPDATE "Settings"
  SET "FK_ThemeID" = (SELECT "ThemeID" FROM "Themes" WHERE "ThemeSlug" = 'classic')
  WHERE "FK_ThemeID" IS NULL;

-- ──────────────────────────────────────────────────────────────
-- AdZones: slot-bazlı reklam snippet yönetimi (AdSense/GAM/direkt HTML)
CREATE TABLE IF NOT EXISTS "AdZones" (
  "AdZoneID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Slot"           TEXT UNIQUE NOT NULL,
  "Label"          TEXT,
  "HtmlSnippet"    TEXT,
  "IsActive"       BOOLEAN DEFAULT FALSE,
  "StartsAt"       TIMESTAMP,
  "EndsAt"         TIMESTAMP,
  "ImpressionNote" TEXT,
  "UpdatedAt"      TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"      INTEGER,
  "IsDeleted"      BOOLEAN DEFAULT FALSE
);
INSERT INTO "AdZones" ("Slot", "Label") VALUES
  ('leaderboard-top',    'Üst banner'),
  ('leaderboard-bottom', 'Alt banner'),
  ('billboard',          'Billboard (ana sayfa orta)'),
  ('sidebar-mpu',        'Kenar MPU'),
  ('sidebar-half',       'Kenar half-page'),
  ('in-article',         'Makale içi')
ON CONFLICT ("Slot") DO NOTHING;

-- ──────────────────────────────────────────────────────────────
-- IndexingLog: Google Indexing API'ye gönderim geçmişi
CREATE TABLE IF NOT EXISTS "IndexingLog" (
  "LogID"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_ContentID" INTEGER,
  "Url"         TEXT NOT NULL,
  "Type"        TEXT NOT NULL,
  "Status"      TEXT NOT NULL,
  "HttpStatus"  INTEGER,
  "Message"     TEXT,
  "SubmittedAt" TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "idx_indexinglog_submitted" ON "IndexingLog" ("SubmittedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_indexinglog_content" ON "IndexingLog" ("FK_ContentID");

-- ──────────────────────────────────────────────────────────────
-- Prompts: sabit AI prompt'larının DB'de saklanması; admin'den düzenlenebilir
CREATE TABLE IF NOT EXISTS "Prompts" (
  "PromptID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PromptKey"   TEXT UNIQUE NOT NULL,
  "Label"       TEXT NOT NULL,
  "Description" TEXT,
  "Template"    TEXT NOT NULL,
  "UpdatedAt"   TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"   INTEGER,
  "IsDeleted"   BOOLEAN DEFAULT FALSE
);

COMMIT;
