-- Basit denetim logu: kim, ne yaptı, nerede, ne zaman.
BEGIN;

CREATE TABLE IF NOT EXISTS "AuditLogs" (
  "LogID"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserName"  TEXT,
  "FK_UserID" INTEGER,
  "Action"    TEXT NOT NULL,
  "Area"      TEXT NOT NULL,
  "CreatedAt" TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_auditlogs_created"
  ON "AuditLogs" ("CreatedAt" DESC);

CREATE INDEX IF NOT EXISTS "idx_auditlogs_area_created"
  ON "AuditLogs" ("Area", "CreatedAt" DESC);

COMMIT;
