-- News fetch drafts. Each row is one article pulled from a news provider
-- (NewsNow, etc.). Drafts are processed by the ingest pipeline: Gemini
-- rewrites them, picks a site category, and on success a Contents row is
-- created and the draft is marked done. Drafts are never garbage-collected
-- automatically — the admin reviews them at /admin/drafts.

BEGIN;

CREATE TABLE IF NOT EXISTS "NewsApiDrafts" (
  "DraftID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Provider"     TEXT NOT NULL,                -- e.g. 'newsnow'
  "ExternalID"   TEXT,                         -- url or provider article id (used for dedupe)
  "RawJSON"      JSONB NOT NULL,               -- original payload from the provider
  "TopImage"     TEXT,                         -- top_image URL extracted from raw
  "SourceTitle"  TEXT,                         -- best-effort source title for the admin UI
  "SourceUrl"    TEXT,                         -- click-through url
  "Status"       TEXT NOT NULL DEFAULT 'pending', -- pending|processing|done|skipped|error
  "FK_CronID"    INTEGER,                      -- which cron job pulled it (nullable for manual fetches)
  "FK_CatID"     INTEGER,                      -- chosen site category after Gemini
  "FK_ContentID" INTEGER,                      -- created Contents row id (when status=done)
  "Message"      TEXT,                         -- error/skip reason
  "FetchedAt"    TIMESTAMP DEFAULT NOW(),
  "ProcessedAt"  TIMESTAMP
);

-- Dedupe per provider+externalId so re-fetches don't create duplicate drafts.
CREATE UNIQUE INDEX IF NOT EXISTS "idx_newsapi_drafts_provider_extid"
  ON "NewsApiDrafts" ("Provider", "ExternalID")
  WHERE "ExternalID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_newsapi_drafts_status_fetched"
  ON "NewsApiDrafts" ("Status", "FetchedAt" DESC);

-- CronJob.Config: provider-specific JSON (NewsNow category, location, language;
-- text-AI model overrides; etc.). Existing jobs default to {} so older rows
-- behave as before.
ALTER TABLE "CronJobs" ADD COLUMN IF NOT EXISTS "Config" JSONB DEFAULT '{}'::jsonb;

COMMIT;
