-- Article generation pipeline:
--   1. SerpAPI fetches trending queries for a seed topic.
--   2. Active "meta" text AI converts each trend into a title + summary +
--      keywords + image prompt → ArticleDrafts row (status=pending).
--   3. Cron tick: active "content" text AI expands each draft into a full
--      HTML body, renders/downloads an image, INSERTS into Contents.
--
-- Cron jobs gain a `Kind` discriminator ('news' | 'article') so a single
-- runner can dispatch to the right pipeline.
--
-- Settings gains three provider knobs that decide WHICH AI handles meta vs
-- full content vs trends. ApiKeys tablosundaki aktif key (provider, purpose)
-- pair'i ile çözülür.

BEGIN;

CREATE TABLE IF NOT EXISTS "ArticleDrafts" (
  "DraftID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_CronID"    INTEGER,
  "FK_CatID"     INTEGER NOT NULL,
  "Title"        TEXT NOT NULL,
  "Summary"      TEXT,
  "Keywords"     TEXT,
  "ImagePrompt"  TEXT,
  "Slug"         TEXT,
  "TrendQuery"   TEXT,
  "Status"       TEXT NOT NULL DEFAULT 'pending',
  "FK_ContentID" INTEGER,
  "Message"      TEXT,
  "CreatedAt"    TIMESTAMP DEFAULT NOW(),
  "ProcessedAt"  TIMESTAMP,
  "Fk_UserID"    INTEGER
);

CREATE INDEX IF NOT EXISTS "idx_articledrafts_status_created"
  ON "ArticleDrafts" ("Status", "CreatedAt" ASC);
CREATE INDEX IF NOT EXISTS "idx_articledrafts_cron"
  ON "ArticleDrafts" ("FK_CronID", "Status");
CREATE INDEX IF NOT EXISTS "idx_articledrafts_cat"
  ON "ArticleDrafts" ("FK_CatID", "Status");

-- Per-row dedupe within the same category. Allows the same title across
-- different categories, but blocks accidental duplicates inside one.
CREATE UNIQUE INDEX IF NOT EXISTS "idx_articledrafts_cat_title"
  ON "ArticleDrafts" ("FK_CatID", LOWER("Title"));

ALTER TABLE "CronJobs"
  ADD COLUMN IF NOT EXISTS "Kind" TEXT NOT NULL DEFAULT 'news';

ALTER TABLE "Settings"
  ADD COLUMN IF NOT EXISTS "MetaProvider"    TEXT;
ALTER TABLE "Settings"
  ADD COLUMN IF NOT EXISTS "ContentProvider" TEXT;
ALTER TABLE "Settings"
  ADD COLUMN IF NOT EXISTS "TrendsProvider"  TEXT;

COMMIT;
