-- Authors: per-byline directory for articles. Auto-created when a category is
-- added; every Content row gets one assigned (manual or via cron).

BEGIN;

CREATE TABLE IF NOT EXISTS "Authors" (
  "AuthorID"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DisplayName"  TEXT NOT NULL,
  "Slug"         TEXT NOT NULL,
  "Bio"          TEXT,
  "AvatarURL"    TEXT,
  "Email"        TEXT,
  "FK_CatID"     INTEGER,
  "IsActive"     BOOLEAN DEFAULT TRUE,
  "IsDeleted"    BOOLEAN DEFAULT FALSE,
  "CreatedDate"  TIMESTAMP DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS "idx_authors_slug"
  ON "Authors" ("Slug")
  WHERE "IsDeleted" = FALSE;

CREATE INDEX IF NOT EXISTS "idx_authors_cat"
  ON "Authors" ("FK_CatID")
  WHERE "IsDeleted" = FALSE AND "IsActive" = TRUE;

ALTER TABLE "Contents" ADD COLUMN IF NOT EXISTS "FK_AuthorID" INTEGER;

CREATE INDEX IF NOT EXISTS "idx_contents_author"
  ON "Contents" ("FK_AuthorID")
  WHERE "IsDeleted" = FALSE;

COMMIT;
