-- Envoraicms — single-file database schema.
--
-- Idempotent: safe to run multiple times on the same database. The /install
-- wizard runs this automatically on first boot; you only need to run it
-- manually via `npm run migrate` for headless / scripted deploys.
--
-- All identity columns use GENERATED BY DEFAULT so dumps / restores can pass
-- explicit IDs via OVERRIDING SYSTEM VALUE. No FK constraints are declared
-- (deletes are soft via IsDeleted).

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────
-- Settings: single-row site configuration. Edited from /admin/settings.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Settings" (
  "SettingsID"                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Identity
  "SiteName"                   TEXT,
  "SiteUrl"                    TEXT,
  "Title"                      TEXT,
  "Description"                TEXT,
  "Keywords"                   TEXT,
  "SiteLanguage"               TEXT DEFAULT 'en',
  "SiteLogo"                   TEXT,
  "Favicon"                    TEXT,
  "CoverImage"                 TEXT,
  "ContentUrl"                 TEXT,
  -- Themes / appearance
  "FK_ThemeID"                 INTEGER,
  "PrimaryColor"               TEXT,
  "SecondaryColor"             TEXT,
  "DefaultColorMode"           TEXT DEFAULT 'light',
  "AllowColorToggle"           BOOLEAN DEFAULT TRUE,
  "ShowHeaderMenu"             BOOLEAN DEFAULT TRUE,
  "ShowFooterMenu"             BOOLEAN DEFAULT TRUE,
  "ShowViewCounts"             BOOLEAN NOT NULL DEFAULT TRUE,
  -- SEO / meta
  "MetaAuthor"                 TEXT,
  "MetaRobots"                 TEXT DEFAULT 'index,follow',
  "TwitterHandle"              TEXT,
  "DefaultOgImage"             TEXT,
  "LlmsTxtEnabled"             BOOLEAN DEFAULT TRUE,
  "LlmsTxtIntro"               TEXT,
  "SocialLinks"                JSONB DEFAULT '[]'::jsonb,
  -- Google services
  "GoogleAnalyticsID"          TEXT,
  "GoogleTagManagerID"         TEXT,
  "SearchConsoleMeta"          TEXT,
  "BingVerification"           TEXT,
  -- AdSense
  "AdsEnabled"                 BOOLEAN DEFAULT TRUE,
  "AdsensePublisherID"         TEXT,
  "AdsenseAutoAds"             BOOLEAN DEFAULT FALSE,
  "AdsenseExtraHead"           TEXT,
  -- Google Indexing API
  "IndexingEnabled"            BOOLEAN DEFAULT FALSE,
  "IndexingServiceAccountJSON" TEXT,
  -- AI provider routing (meta, content, trends)
  "MetaProvider"               TEXT,
  "ContentProvider"            TEXT,
  "TrendsProvider"             TEXT,
  -- Misc / advanced
  "HeaderScripts"              TEXT,
  "SessionSecret"              TEXT,  -- generated by /install; rotate via UPDATE + restart
  "MailServer"                 TEXT,
  "MailSender"                 TEXT,
  "MailPassword"               TEXT,
  "CdnServer"                  TEXT,
  "CdnFtpUser"                 TEXT,
  "CdnFtpPassword"             TEXT,
  "XApiEnabled"                BOOLEAN DEFAULT FALSE,
  -- Audit
  "FK_LangID"                  INTEGER,
  "Fk_UserID"                  INTEGER,
  "CreatedDate"                TIMESTAMP,
  "IsDeleted"                  BOOLEAN DEFAULT FALSE
);

-- ─────────────────────────────────────────────────────────────────────────
-- Categories: nav + filing taxonomy. Authors and Contents reference these.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Categories" (
  "CatID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CatName"      TEXT,
  "CatTitle"     TEXT,
  "CatKeywords"  TEXT,
  "CatDesc"      TEXT,
  "CatURL"       TEXT,
  "CatSeo"       TEXT,
  "CatImage"     TEXT,
  "CatNumber"    INTEGER,
  "HeaderMenu"   BOOLEAN DEFAULT FALSE,
  "FooterMenu"   BOOLEAN DEFAULT FALSE,
  "SideMenu"     BOOLEAN DEFAULT FALSE,
  "DropdownMenu" BOOLEAN DEFAULT FALSE,
  "ParentCatID"  INTEGER DEFAULT 0,
  "FK_LangID"    INTEGER,
  "Fk_UserID"    INTEGER,
  "IsActive"     BOOLEAN DEFAULT TRUE,
  "IsDeleted"    BOOLEAN DEFAULT FALSE,
  "CreatedDate"  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "idx_categories_seo" ON "Categories" ("CatSeo")
  WHERE "IsActive" AND NOT "IsDeleted";

-- ─────────────────────────────────────────────────────────────────────────
-- Authors: per-byline directory shown on each article.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Authors" (
  "AuthorID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DisplayName" TEXT NOT NULL,
  "Slug"        TEXT NOT NULL,
  "Bio"         TEXT,
  "AvatarURL"   TEXT,
  "Email"       TEXT,
  "FK_CatID"    INTEGER,
  "IsActive"    BOOLEAN DEFAULT TRUE,
  "IsDeleted"   BOOLEAN DEFAULT FALSE,
  "CreatedDate" TIMESTAMP DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_authors_slug" ON "Authors" ("Slug")
  WHERE "IsDeleted" = FALSE;
CREATE INDEX IF NOT EXISTS "idx_authors_cat" ON "Authors" ("FK_CatID")
  WHERE "IsDeleted" = FALSE AND "IsActive" = TRUE;

-- ─────────────────────────────────────────────────────────────────────────
-- Contents: articles. Soft-delete via IsDeleted.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Contents" (
  "ContentID"             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_CatID"              INTEGER,
  "FK_AuthorID"           INTEGER,
  "FK_LangID"             INTEGER,
  "ContentTitle"          TEXT,
  "ContentShort"          TEXT,
  "ContentDetail"         TEXT,
  "ContentAlternateTitle" TEXT,
  "ContentOriginalTitle"  TEXT,
  "ContentKeywords"       TEXT,
  "ContentDesc"           TEXT,
  "ContentImage"          TEXT,
  "ImagePrompt"           TEXT,
  "ContentVideo"          TEXT,
  "ContentSeo"            TEXT,
  "ContentURL"            TEXT,
  "ContentSource"         TEXT,
  "ContentNumber"         INTEGER,
  "ViewCount"             BIGINT DEFAULT 0,
  "HeaderMenu"            BOOLEAN DEFAULT FALSE,
  "FooterMenu"            BOOLEAN DEFAULT FALSE,
  "SideMenu"              BOOLEAN DEFAULT FALSE,
  "Homepage"              BOOLEAN DEFAULT FALSE,
  "IsActive"              BOOLEAN DEFAULT TRUE,
  "IsDeleted"             BOOLEAN DEFAULT FALSE,
  "Fk_UserID"             INTEGER,
  "PublishDate"           TIMESTAMP,
  "ModifiedDate"          TIMESTAMP,
  "CreatedDate"           TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "idx_contents_seo" ON "Contents" ("ContentSeo")
  WHERE "IsActive" AND NOT "IsDeleted";
CREATE INDEX IF NOT EXISTS "idx_contents_cat_date" ON "Contents" ("FK_CatID", "PublishDate" DESC)
  WHERE "IsActive" AND NOT "IsDeleted";
CREATE INDEX IF NOT EXISTS "idx_contents_homepage" ON "Contents" ("PublishDate" DESC)
  WHERE "IsActive" AND NOT "IsDeleted" AND "Homepage";
CREATE INDEX IF NOT EXISTS "idx_contents_publish" ON "Contents" ("PublishDate" DESC)
  WHERE "IsActive" AND NOT "IsDeleted";
CREATE INDEX IF NOT EXISTS "idx_contents_author" ON "Contents" ("FK_AuthorID")
  WHERE "IsDeleted" = FALSE;
CREATE INDEX IF NOT EXISTS "idx_contents_cat_created" ON "Contents" ("FK_CatID", "CreatedDate" DESC)
  WHERE NOT "IsDeleted";
CREATE INDEX IF NOT EXISTS "idx_contents_viewcount"
  ON "Contents" ("ViewCount" DESC NULLS LAST, "PublishDate" DESC)
  WHERE "IsActive" AND NOT "IsDeleted";
-- Trigram index for admin substring search (ILIKE on ContentTitle).
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS "idx_contents_title_trgm"
  ON "Contents" USING gin ("ContentTitle" gin_trgm_ops)
  WHERE "IsActive" AND NOT "IsDeleted";
-- Full-text search index (alternative to trigram, kept for fallback).
CREATE INDEX IF NOT EXISTS "idx_contents_fts"
  ON "Contents" USING gin (
    to_tsvector('english',
      coalesce("ContentTitle",'') || ' ' ||
      coalesce("ContentDesc",'') || ' ' ||
      coalesce("ContentKeywords",'')
    )
  );

-- ─────────────────────────────────────────────────────────────────────────
-- Themes: site templates. Seeded with the three first-party themes.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Themes" (
  "ThemeID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ThemeSlug"    TEXT UNIQUE NOT NULL,
  "ThemeName"    TEXT NOT NULL,
  "ThemeDesc"    TEXT,
  "PreviewImage" TEXT,
  "Config"       JSONB DEFAULT '{}'::jsonb,
  "SupportsDark" BOOLEAN DEFAULT TRUE,
  "IsActive"     BOOLEAN DEFAULT TRUE,
  "IsDeleted"    BOOLEAN DEFAULT FALSE,
  "CreatedDate"  TIMESTAMP DEFAULT NOW()
);
INSERT INTO "Themes" ("ThemeSlug", "ThemeName", "ThemeDesc", "SupportsDark") VALUES
  ('classic',  'Editorial Grid', 'Hero carousel up top, then category duos, hot-now strip, and tall-feature columns.', TRUE),
  ('magazine', 'Cover Mosaic',   'Three-column overlay mosaic with a dominant cover; image-driven feel.',              TRUE),
  ('minimal',  'Broadsheet',     'Top headline strip, big lead with sidebar list, then dense category columns.',       TRUE)
ON CONFLICT ("ThemeSlug") DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- Users: admin + editor accounts. Created by /install + /admin/users.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Users" (
  "UserID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Email"        TEXT UNIQUE NOT NULL,
  "Username"     TEXT UNIQUE,
  "PasswordHash" TEXT NOT NULL,
  "DisplayName"  TEXT,
  "Role"         TEXT NOT NULL DEFAULT 'editor',
  "AvatarURL"    TEXT,
  "LastLoginAt"  TIMESTAMP,
  "IsActive"     BOOLEAN DEFAULT TRUE,
  "IsDeleted"    BOOLEAN DEFAULT FALSE,
  "CreatedDate"  TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"    INTEGER
);

-- ─────────────────────────────────────────────────────────────────────────
-- Links: static pages + custom nav links (combined in one table).
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Links" (
  "LinkID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LinkTitle"   TEXT,
  "Link"        TEXT,
  "LinkIcon"    TEXT,
  "LinkSeo"     TEXT,
  "LinkContent" TEXT,
  "LinkNumber"  INTEGER,
  "TopMenu"     BOOLEAN DEFAULT FALSE,
  "Footer"      BOOLEAN DEFAULT FALSE,
  "IsActive"    BOOLEAN DEFAULT TRUE,
  "IsDeleted"   BOOLEAN DEFAULT FALSE,
  "Fk_LangID"   INTEGER,
  "Fk_UserID"   INTEGER,
  "CreatedDate" TIMESTAMP
);

-- ─────────────────────────────────────────────────────────────────────────
-- ApiKeys: encrypted API keys for AI / news / trends providers.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "ApiKeys" (
  "ApiKeyID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Provider"    TEXT NOT NULL,
  "Purpose"     TEXT NOT NULL,
  "Label"       TEXT,
  "KeyValue"    TEXT NOT NULL,
  "Config"      JSONB DEFAULT '{}'::jsonb,
  "IsActive"    BOOLEAN DEFAULT FALSE,
  "IsDeleted"   BOOLEAN DEFAULT FALSE,
  "CreatedDate" TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"   INTEGER
);
-- One active key per (provider, purpose) tuple.
CREATE UNIQUE INDEX IF NOT EXISTS "idx_apikeys_active_per_purpose"
  ON "ApiKeys" ("Provider", "Purpose")
  WHERE "IsActive" = TRUE AND "IsDeleted" = FALSE;

-- ─────────────────────────────────────────────────────────────────────────
-- CronJobs: scheduled news / article pipelines per category.
-- Kind = 'news' (NewsNow rewrite) or 'article' (SerpAPI → AI ideation).
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "CronJobs" (
  "CronID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "JobName"         TEXT NOT NULL,
  "Kind"            TEXT NOT NULL DEFAULT 'news',
  "FK_CatID"        INTEGER,
  "NewsProvider"    TEXT,
  "TextAiProvider"  TEXT,
  "ImageAiProvider" TEXT,
  "FrequencyCron"   TEXT NOT NULL,
  "ArticlesPerRun"  INTEGER DEFAULT 3,
  "Config"          JSONB DEFAULT '{}'::jsonb,
  "LastRunAt"       TIMESTAMP,
  "LastRunStatus"   TEXT,
  "LastRunMessage"  TEXT,
  "NextRunAt"       TIMESTAMP,
  "IsActive"        BOOLEAN DEFAULT TRUE,
  "IsDeleted"       BOOLEAN DEFAULT FALSE,
  "CreatedDate"     TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"       INTEGER
);
CREATE INDEX IF NOT EXISTS "idx_cronjobs_due" ON "CronJobs" ("NextRunAt")
  WHERE "IsActive" = TRUE AND "IsDeleted" = FALSE;

-- ─────────────────────────────────────────────────────────────────────────
-- ArticleDrafts: pending AI-generated article drafts (SerpAPI → AI pipeline).
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "ArticleDrafts" (
  "DraftID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_CronID"    INTEGER,
  "FK_CatID"     INTEGER NOT NULL,
  "Title"        TEXT NOT NULL,
  "Summary"      TEXT,
  "Keywords"     TEXT,
  "ImagePrompt"  TEXT,
  "Slug"         TEXT,
  "TrendQuery"   TEXT,
  "Status"       TEXT NOT NULL DEFAULT 'pending',
  "FK_ContentID" INTEGER,
  "Message"      TEXT,
  "CreatedAt"    TIMESTAMP DEFAULT NOW(),
  "ProcessedAt"  TIMESTAMP,
  "Fk_UserID"    INTEGER
);
CREATE INDEX IF NOT EXISTS "idx_articledrafts_status_created"
  ON "ArticleDrafts" ("Status", "CreatedAt" ASC);
CREATE INDEX IF NOT EXISTS "idx_articledrafts_cron"
  ON "ArticleDrafts" ("FK_CronID", "Status");
CREATE INDEX IF NOT EXISTS "idx_articledrafts_cat"
  ON "ArticleDrafts" ("FK_CatID", "Status");
CREATE INDEX IF NOT EXISTS "idx_articledrafts_cat_created"
  ON "ArticleDrafts" ("FK_CatID", "CreatedAt" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_articledrafts_cat_title"
  ON "ArticleDrafts" ("FK_CatID", LOWER("Title"));

-- ─────────────────────────────────────────────────────────────────────────
-- NewsApiDrafts: raw news items from NewsNow before AI rewrite.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "NewsApiDrafts" (
  "DraftID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Provider"     TEXT NOT NULL,
  "ExternalID"   TEXT,
  "RawJSON"      JSONB NOT NULL,
  "TopImage"     TEXT,
  "SourceTitle"  TEXT,
  "SourceUrl"    TEXT,
  "Status"       TEXT NOT NULL DEFAULT 'pending',
  "FK_CronID"    INTEGER,
  "FK_CatID"     INTEGER,
  "FK_ContentID" INTEGER,
  "Message"      TEXT,
  "FetchedAt"    TIMESTAMP DEFAULT NOW(),
  "ProcessedAt"  TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_newsapi_drafts_provider_extid"
  ON "NewsApiDrafts" ("Provider", "ExternalID")
  WHERE "ExternalID" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_newsapi_drafts_status_fetched"
  ON "NewsApiDrafts" ("Status", "FetchedAt" DESC);

-- ─────────────────────────────────────────────────────────────────────────
-- IngestRuns: per-cron-tick run log. Shown in /admin/logs.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "IngestRuns" (
  "RunID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_CronID"  INTEGER,
  "FK_CatID"   INTEGER,
  "StartedAt"  TIMESTAMP DEFAULT NOW(),
  "FinishedAt" TIMESTAMP,
  "Inserted"   INTEGER DEFAULT 0,
  "Skipped"    INTEGER DEFAULT 0,
  "Errored"    INTEGER DEFAULT 0,
  "Status"     TEXT,
  "Log"        TEXT
);
CREATE INDEX IF NOT EXISTS "idx_ingestruns_started" ON "IngestRuns" ("StartedAt" DESC);

-- ─────────────────────────────────────────────────────────────────────────
-- IndexingLog: Google Search Console Indexing API call history.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "IndexingLog" (
  "LogID"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_ContentID" INTEGER,
  "Url"          TEXT NOT NULL,
  "Type"         TEXT NOT NULL,
  "Status"       TEXT NOT NULL,
  "HttpStatus"   INTEGER,
  "Message"      TEXT,
  "SubmittedAt"  TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "idx_indexinglog_submitted" ON "IndexingLog" ("SubmittedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_indexinglog_content" ON "IndexingLog" ("FK_ContentID");

-- ─────────────────────────────────────────────────────────────────────────
-- Prompts: editable AI prompt templates. Keyed by PromptKey.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Prompts" (
  "PromptID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PromptKey"   TEXT UNIQUE NOT NULL,
  "Label"       TEXT NOT NULL,
  "Description" TEXT,
  "Template"    TEXT NOT NULL,
  "UpdatedAt"   TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"   INTEGER,
  "IsDeleted"   BOOLEAN DEFAULT FALSE
);

-- ─────────────────────────────────────────────────────────────────────────
-- AdZones: configurable ad placements. Seeded with the built-in slots.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "AdZones" (
  "AdZoneID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Slot"           TEXT UNIQUE NOT NULL,
  "Label"          TEXT,
  "HtmlSnippet"    TEXT,
  "IsActive"       BOOLEAN DEFAULT FALSE,
  "StartsAt"       TIMESTAMP,
  "EndsAt"         TIMESTAMP,
  "ImpressionNote" TEXT,
  "UpdatedAt"      TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"      INTEGER,
  "IsDeleted"      BOOLEAN DEFAULT FALSE
);
INSERT INTO "AdZones" ("Slot", "Label") VALUES
  ('leaderboard-top',    'Top leaderboard'),
  ('leaderboard-bottom', 'Bottom leaderboard'),
  ('billboard',          'Billboard (homepage middle)'),
  ('sidebar-mpu',        'Sidebar MPU'),
  ('sidebar-half',       'Sidebar half-page'),
  ('in-article',         'In-article')
ON CONFLICT ("Slot") DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- AuditLogs: trail of admin actions. Shown in /admin/logs.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "AuditLogs" (
  "LogID"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserName"  TEXT,
  "FK_UserID" INTEGER,
  "Action"    TEXT NOT NULL,
  "Area"      TEXT NOT NULL,
  "CreatedAt" TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "idx_auditlogs_created"
  ON "AuditLogs" ("CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_auditlogs_area_created"
  ON "AuditLogs" ("Area", "CreatedAt" DESC);

-- ─────────────────────────────────────────────────────────────────────────
-- LoginAttempts: brute-force guard. An IP with 5+ failures in the last
-- 15 minutes is temporarily locked out of /admin/login.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "LoginAttempts" (
  "AttemptID"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IP"          TEXT NOT NULL,
  "Email"       TEXT,
  "Success"     BOOLEAN NOT NULL,
  "CreatedDate" TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "idx_loginattempts_ip_created"
  ON "LoginAttempts" ("IP", "CreatedDate" DESC);

COMMIT;
