-- Minimal schema reconstructed from dump (pg_dump 17.2 was data-only).
-- Phase-1 tables + Links (static pages + nav links live in one table).
-- No FK constraints (other tables not restored); identity columns use
-- GENERATED BY DEFAULT so the dump's OVERRIDING SYSTEM VALUE still works.

BEGIN;

CREATE TABLE IF NOT EXISTS "Settings" (
  "SettingsID"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title"          TEXT,
  "Description"    TEXT,
  "Keywords"       TEXT,
  "MailServer"     TEXT,
  "MailSender"     TEXT,
  "MailPassword"   TEXT,
  "FK_LangID"      INTEGER,
  "Fk_UserID"      INTEGER,
  "CreatedDate"    TIMESTAMP,
  "IsDeleted"      BOOLEAN DEFAULT FALSE,
  "CdnServer"      TEXT,
  "CdnFtpUser"     TEXT,
  "CdnFtpPassword" TEXT,
  "XApiEnabled"    BOOLEAN DEFAULT FALSE,
  "HeaderScripts"  TEXT,
  "SiteName"       TEXT,
  "SiteUrl"        TEXT,
  "CoverImage"     TEXT,
  "ContentUrl"     TEXT,
  "SiteLogo"       TEXT,
  "AdsEnabled"     BOOLEAN DEFAULT TRUE
);

ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AdsEnabled" BOOLEAN DEFAULT TRUE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AdsensePublisherID" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AdsenseAutoAds"     BOOLEAN DEFAULT FALSE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AdsenseExtraHead"   TEXT;

CREATE TABLE IF NOT EXISTS "Categories" (
  "CatID"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_LangID"     INTEGER,
  "CatName"       TEXT,
  "CatTitle"      TEXT,
  "CatKeywords"   TEXT,
  "CatDesc"       TEXT,
  "CatURL"        TEXT,
  "CatSeo"        TEXT,
  "CatImage"      TEXT,
  "CatNumber"     INTEGER,
  "HeaderMenu"    BOOLEAN DEFAULT FALSE,
  "FooterMenu"    BOOLEAN DEFAULT FALSE,
  "SideMenu"      BOOLEAN DEFAULT FALSE,
  "DropdownMenu"  BOOLEAN DEFAULT FALSE,
  "IsActive"      BOOLEAN DEFAULT TRUE,
  "Fk_UserID"     INTEGER,
  "CreatedDate"   TIMESTAMP,
  "IsDeleted"     BOOLEAN DEFAULT FALSE,
  "ParentCatID"   INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "Contents" (
  "ContentID"             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_CatID"              INTEGER,
  "FK_LangID"             INTEGER,
  "ContentTitle"          TEXT,
  "ContentShort"          TEXT,
  "ContentDetail"         TEXT,
  "ContentAlternateTitle" TEXT,
  "ContentOriginalTitle"  TEXT,
  "ContentKeywords"       TEXT,
  "ContentDesc"           TEXT,
  "ContentImage"          TEXT,
  "ImagePrompt"           TEXT,
  "ViewCount"             BIGINT DEFAULT 0,
  "ContentVideo"          TEXT,
  "ContentSeo"            TEXT,
  "ContentURL"            TEXT,
  "ContentSource"         TEXT,
  "ContentNumber"         INTEGER,
  "HeaderMenu"            BOOLEAN DEFAULT FALSE,
  "FooterMenu"            BOOLEAN DEFAULT FALSE,
  "SideMenu"              BOOLEAN DEFAULT FALSE,
  "Homepage"              BOOLEAN DEFAULT FALSE,
  "IsActive"              BOOLEAN DEFAULT TRUE,
  "Fk_UserID"             INTEGER,
  "PublishDate"           TIMESTAMP,
  "ModifiedDate"          TIMESTAMP,
  "CreatedDate"           TIMESTAMP,
  "IsDeleted"             BOOLEAN DEFAULT FALSE
);
ALTER TABLE "Contents" ADD COLUMN IF NOT EXISTS "ModifiedDate" TIMESTAMP;

CREATE TABLE IF NOT EXISTS "Links" (
  "LinkID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LinkTitle"    TEXT,
  "Link"         TEXT,
  "LinkIcon"     TEXT,
  "LinkNumber"   INTEGER,
  "TopMenu"      BOOLEAN DEFAULT FALSE,
  "Footer"       BOOLEAN DEFAULT FALSE,
  "IsActive"     BOOLEAN DEFAULT TRUE,
  "CreatedDate"  TIMESTAMP,
  "Fk_LangID"    INTEGER,
  "Fk_UserID"    INTEGER,
  "LinkContent"  TEXT,
  "LinkSeo"      TEXT,
  "IsDeleted"    BOOLEAN DEFAULT FALSE
);

ALTER TABLE "Links" ADD COLUMN IF NOT EXISTS "LinkNumber" INTEGER;

-- ──────────────────────────────────────────────────────────────
-- Dinamik platform tabloları (bkz. deploy/migrations/002_dynamic.sql).
-- Yeni kurulumlarda tek dosyadan çalışabilsin diye burada da var.

CREATE TABLE IF NOT EXISTS "Users" (
  "UserID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Email"         TEXT UNIQUE NOT NULL,
  "Username"      TEXT UNIQUE,
  "PasswordHash"  TEXT NOT NULL,
  "DisplayName"   TEXT,
  "Role"          TEXT NOT NULL DEFAULT 'editor',
  "AvatarURL"     TEXT,
  "LastLoginAt"   TIMESTAMP,
  "IsActive"      BOOLEAN DEFAULT TRUE,
  "IsDeleted"     BOOLEAN DEFAULT FALSE,
  "CreatedDate"   TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"     INTEGER
);

CREATE TABLE IF NOT EXISTS "ApiKeys" (
  "ApiKeyID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Provider"      TEXT NOT NULL,
  "Purpose"       TEXT NOT NULL,
  "Label"         TEXT,
  "KeyValue"      TEXT NOT NULL,
  "Config"        JSONB DEFAULT '{}'::jsonb,
  "IsActive"      BOOLEAN DEFAULT FALSE,
  "IsDeleted"     BOOLEAN DEFAULT FALSE,
  "CreatedDate"   TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"     INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_apikeys_active_per_purpose"
  ON "ApiKeys" ("Provider", "Purpose")
  WHERE "IsActive" = TRUE AND "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "CronJobs" (
  "CronID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "JobName"         TEXT NOT NULL,
  "FK_CatID"        INTEGER,
  "NewsProvider"    TEXT,
  "TextAiProvider"  TEXT,
  "ImageAiProvider" TEXT,
  "FrequencyCron"   TEXT NOT NULL,
  "ArticlesPerRun"  INTEGER DEFAULT 3,
  "Config"          JSONB DEFAULT '{}'::jsonb,
  "LastRunAt"       TIMESTAMP,
  "LastRunStatus"   TEXT,
  "LastRunMessage"  TEXT,
  "NextRunAt"       TIMESTAMP,
  "IsActive"        BOOLEAN DEFAULT TRUE,
  "IsDeleted"       BOOLEAN DEFAULT FALSE,
  "CreatedDate"     TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"       INTEGER
);
CREATE INDEX IF NOT EXISTS "idx_cronjobs_due"
  ON "CronJobs" ("NextRunAt")
  WHERE "IsActive" = TRUE AND "IsDeleted" = FALSE;

CREATE TABLE IF NOT EXISTS "Themes" (
  "ThemeID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ThemeSlug"     TEXT UNIQUE NOT NULL,
  "ThemeName"     TEXT NOT NULL,
  "ThemeDesc"     TEXT,
  "PreviewImage"  TEXT,
  "Config"        JSONB DEFAULT '{}'::jsonb,
  "SupportsDark"  BOOLEAN DEFAULT TRUE,
  "IsActive"      BOOLEAN DEFAULT TRUE,
  "IsDeleted"     BOOLEAN DEFAULT FALSE,
  "CreatedDate"   TIMESTAMP DEFAULT NOW()
);
INSERT INTO "Themes" ("ThemeSlug", "ThemeName", "ThemeDesc", "SupportsDark") VALUES
  ('classic',  'Classic',  'Varsayılan hero + grid',              TRUE),
  ('magazine', 'Magazine', '2 kolonlu büyük kapak + yan sidebar', TRUE),
  ('minimal',  'Minimal',  'Tek kolon yalın liste',               TRUE)
ON CONFLICT ("ThemeSlug") DO NOTHING;

CREATE TABLE IF NOT EXISTS "IngestRuns" (
  "RunID"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_CronID"   INTEGER,
  "FK_CatID"    INTEGER,
  "StartedAt"   TIMESTAMP DEFAULT NOW(),
  "FinishedAt"  TIMESTAMP,
  "Inserted"    INTEGER DEFAULT 0,
  "Skipped"     INTEGER DEFAULT 0,
  "Errored"     INTEGER DEFAULT 0,
  "Status"      TEXT,
  "Log"         TEXT
);
CREATE INDEX IF NOT EXISTS "idx_ingestruns_started" ON "IngestRuns" ("StartedAt" DESC);

ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "GoogleAnalyticsID"  TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "GoogleTagManagerID" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "SearchConsoleMeta"  TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "BingVerification"   TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "DefaultOgImage"     TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "TwitterHandle"      TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "MetaAuthor"         TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "MetaRobots"         TEXT DEFAULT 'index,follow';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "FK_ThemeID"         INTEGER;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "DefaultColorMode"   TEXT DEFAULT 'light';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "AllowColorToggle"   BOOLEAN DEFAULT TRUE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "LlmsTxtEnabled"     BOOLEAN DEFAULT TRUE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "LlmsTxtIntro"       TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "SocialLinks"        JSONB DEFAULT '[]'::jsonb;

ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "IndexingEnabled"            BOOLEAN DEFAULT FALSE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "IndexingServiceAccountJSON" TEXT;

-- Session cookie imzalama secret'ı. Kurulumda installer üretir; .env'e
-- KOPYALAMAYA gerek yok. Rotasyon = bu kolonu UPDATE + node restart.
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "SessionSecret" TEXT;

ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "Favicon" TEXT;

-- Provider seçimi: meta, content, trends üretimi için aktif AI servisi.
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "MetaProvider"    TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ContentProvider" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "TrendsProvider"  TEXT;

-- News pipeline ile Article pipeline arasındaki discriminator.
ALTER TABLE "CronJobs" ADD COLUMN IF NOT EXISTS "Kind" TEXT NOT NULL DEFAULT 'news';

CREATE TABLE IF NOT EXISTS "ArticleDrafts" (
  "DraftID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_CronID"    INTEGER,
  "FK_CatID"     INTEGER NOT NULL,
  "Title"        TEXT NOT NULL,
  "Summary"      TEXT,
  "Keywords"     TEXT,
  "ImagePrompt"  TEXT,
  "Slug"         TEXT,
  "TrendQuery"   TEXT,
  "Status"       TEXT NOT NULL DEFAULT 'pending',
  "FK_ContentID" INTEGER,
  "Message"      TEXT,
  "CreatedAt"    TIMESTAMP DEFAULT NOW(),
  "ProcessedAt"  TIMESTAMP,
  "Fk_UserID"    INTEGER
);
CREATE INDEX IF NOT EXISTS "idx_articledrafts_status_created"
  ON "ArticleDrafts" ("Status", "CreatedAt" ASC);
CREATE INDEX IF NOT EXISTS "idx_articledrafts_cron"
  ON "ArticleDrafts" ("FK_CronID", "Status");
CREATE INDEX IF NOT EXISTS "idx_articledrafts_cat"
  ON "ArticleDrafts" ("FK_CatID", "Status");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_articledrafts_cat_title"
  ON "ArticleDrafts" ("FK_CatID", LOWER("Title"));

CREATE TABLE IF NOT EXISTS "NewsApiDrafts" (
  "DraftID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Provider"     TEXT NOT NULL,
  "ExternalID"   TEXT,
  "RawJSON"      JSONB NOT NULL,
  "TopImage"     TEXT,
  "SourceTitle"  TEXT,
  "SourceUrl"    TEXT,
  "Status"       TEXT NOT NULL DEFAULT 'pending',
  "FK_CronID"    INTEGER,
  "FK_CatID"     INTEGER,
  "FK_ContentID" INTEGER,
  "Message"      TEXT,
  "FetchedAt"    TIMESTAMP DEFAULT NOW(),
  "ProcessedAt"  TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_newsapi_drafts_provider_extid"
  ON "NewsApiDrafts" ("Provider", "ExternalID")
  WHERE "ExternalID" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_newsapi_drafts_status_fetched"
  ON "NewsApiDrafts" ("Status", "FetchedAt" DESC);

CREATE TABLE IF NOT EXISTS "IndexingLog" (
  "LogID"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FK_ContentID" INTEGER,
  "Url"          TEXT NOT NULL,
  "Type"         TEXT NOT NULL,
  "Status"       TEXT NOT NULL,
  "HttpStatus"   INTEGER,
  "Message"      TEXT,
  "SubmittedAt"  TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "idx_indexinglog_submitted" ON "IndexingLog" ("SubmittedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_indexinglog_content" ON "IndexingLog" ("FK_ContentID");

CREATE TABLE IF NOT EXISTS "Prompts" (
  "PromptID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PromptKey"   TEXT UNIQUE NOT NULL,
  "Label"       TEXT NOT NULL,
  "Description" TEXT,
  "Template"    TEXT NOT NULL,
  "UpdatedAt"   TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"   INTEGER,
  "IsDeleted"   BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "AdZones" (
  "AdZoneID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Slot"           TEXT UNIQUE NOT NULL,
  "Label"          TEXT,
  "HtmlSnippet"    TEXT,
  "IsActive"       BOOLEAN DEFAULT FALSE,
  "StartsAt"       TIMESTAMP,
  "EndsAt"         TIMESTAMP,
  "ImpressionNote" TEXT,
  "UpdatedAt"      TIMESTAMP DEFAULT NOW(),
  "Fk_UserID"      INTEGER,
  "IsDeleted"      BOOLEAN DEFAULT FALSE
);
INSERT INTO "AdZones" ("Slot", "Label") VALUES
  ('leaderboard-top',    'Üst banner'),
  ('leaderboard-bottom', 'Alt banner'),
  ('billboard',          'Billboard (ana sayfa orta)'),
  ('sidebar-mpu',        'Kenar MPU'),
  ('sidebar-half',       'Kenar half-page'),
  ('in-article',         'Makale içi')
ON CONFLICT ("Slot") DO NOTHING;

CREATE TABLE IF NOT EXISTS "AuditLogs" (
  "LogID"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserName"  TEXT,
  "FK_UserID" INTEGER,
  "Action"    TEXT NOT NULL,
  "Area"      TEXT NOT NULL,
  "CreatedAt" TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "idx_auditlogs_created"
  ON "AuditLogs" ("CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_auditlogs_area_created"
  ON "AuditLogs" ("Area", "CreatedAt" DESC);

-- Authors: per-byline directory. Auto-created on category insert; every Content
-- row gets one assigned. Mirrors deploy/migrations/009_authors.sql.
CREATE TABLE IF NOT EXISTS "Authors" (
  "AuthorID"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DisplayName"  TEXT NOT NULL,
  "Slug"         TEXT NOT NULL,
  "Bio"          TEXT,
  "AvatarURL"    TEXT,
  "Email"        TEXT,
  "FK_CatID"     INTEGER,
  "IsActive"     BOOLEAN DEFAULT TRUE,
  "IsDeleted"    BOOLEAN DEFAULT FALSE,
  "CreatedDate"  TIMESTAMP DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_authors_slug"
  ON "Authors" ("Slug")
  WHERE "IsDeleted" = FALSE;
CREATE INDEX IF NOT EXISTS "idx_authors_cat"
  ON "Authors" ("FK_CatID")
  WHERE "IsDeleted" = FALSE AND "IsActive" = TRUE;

ALTER TABLE "Contents" ADD COLUMN IF NOT EXISTS "FK_AuthorID" INTEGER;
CREATE INDEX IF NOT EXISTS "idx_contents_author"
  ON "Contents" ("FK_AuthorID")
  WHERE "IsDeleted" = FALSE;

-- Mirrors deploy/migrations/010_menu_toggles.sql.
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ShowHeaderMenu" BOOLEAN DEFAULT TRUE;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ShowFooterMenu" BOOLEAN DEFAULT TRUE;

COMMIT;
