import "server-only";
import { cookies } from "next/headers";
import { sql } from "@/lib/db";
import { encrypt, decrypt } from "./crypto";

// AES-GCM encrypted cookie. A local, dep-free alternative to iron-session.
// Payload: { uid, role, exp }. Cookie name: envoraicms_admin.
//
// Secret source order:
//   1. process.env.SESSION_SECRET (legacy, kept for back-compat)
//   2. Settings.SessionSecret (generated by /install on first run)
// Module-level memory cache; first request hits DB, the rest are cached.

const COOKIE_NAME = "envoraicms_admin";
const SESSION_TTL_SEC = 60 * 60 * 24 * 7; // 7 days

export type Session = {
  uid: number;
  role: "admin" | "editor" | "viewer";
  email: string;
  displayName: string | null;
  exp: number; // unix seconds
};

let cachedSecret: string | null = null;

async function getSessionSecret(): Promise<string> {
  if (cachedSecret) return cachedSecret;

  const fromEnv = process.env.SESSION_SECRET;
  if (fromEnv && fromEnv.length >= 16) {
    cachedSecret = fromEnv;
    return cachedSecret;
  }

  try {
    const rows = await sql<{ SessionSecret: string | null }[]>`
      SELECT "SessionSecret" FROM "Settings" WHERE "IsDeleted" = FALSE LIMIT 1
    `;
    const fromDb = rows[0]?.SessionSecret;
    if (fromDb && fromDb.length >= 16) {
      cachedSecret = fromDb;
      return cachedSecret;
    }
  } catch {
    /* Settings table missing or DB unreachable → install required */
  }

  throw new Error("Session secret not initialized. Run /install.");
}

// For tests and install routes: refresh the cache after generating a new secret.
export function refreshSessionSecretCache(secret: string): void {
  cachedSecret = secret;
}

export async function setSession(payload: Omit<Session, "exp">): Promise<void> {
  const exp = Math.floor(Date.now() / 1000) + SESSION_TTL_SEC;
  const full: Session = { ...payload, exp };
  const secret = await getSessionSecret();
  const value = encrypt(JSON.stringify(full), secret);
  const c = await cookies();
  c.set(COOKIE_NAME, value, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: SESSION_TTL_SEC,
  });
}

export async function clearSession(): Promise<void> {
  const c = await cookies();
  c.delete(COOKIE_NAME);
}

export async function getSession(): Promise<Session | null> {
  const c = await cookies();
  const raw = c.get(COOKIE_NAME)?.value;
  if (!raw) return null;
  try {
    const secret = await getSessionSecret();
    const json = decrypt(raw, secret);
    const s = JSON.parse(json) as Session;
    if (s.exp * 1000 < Date.now()) return null;
    return s;
  } catch {
    return null;
  }
}

export async function requireSession(): Promise<Session> {
  const s = await getSession();
  if (!s) throw new Error("UNAUTHENTICATED");
  return s;
}

export async function requireRole(roles: Session["role"][]): Promise<Session> {
  const s = await requireSession();
  if (!roles.includes(s.role)) throw new Error("FORBIDDEN");
  return s;
}
